kind: Service                             
apiVersion: v1
metadata:
  name: oggyhere
  labels:
    app: oggyhere
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: oggyhere                    
  type: LoadBalancer